// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRFIeTu7kP3KBgEc9sxvLweRzGaXPR-Ys',
    appId: '1:680599013508:web:d8b33cf326770719aa9ad1',
    messagingSenderId: '680599013508',
    projectId: 'link-tree-27990',
    authDomain: 'link-tree-27990.firebaseapp.com',
    storageBucket: 'link-tree-27990.appspot.com',
    measurementId: 'G-D46BZ89260',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVlG2MfV5r2qMR5siBoWvzTZVq-ZtowBs',
    appId: '1:680599013508:android:f0af5aa553a4a55aaa9ad1',
    messagingSenderId: '680599013508',
    projectId: 'link-tree-27990',
    storageBucket: 'link-tree-27990.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFsZfWEuo6gxUiMA0_k-InFH1P3nLguCU',
    appId: '1:680599013508:ios:23d2303aaaf788e3aa9ad1',
    messagingSenderId: '680599013508',
    projectId: 'link-tree-27990',
    storageBucket: 'link-tree-27990.appspot.com',
    iosClientId: '680599013508-5kb8koa7jb4rot0fc3t4ti9ubqggusmp.apps.googleusercontent.com',
    iosBundleId: 'link.tree',
  );
}
